### ISSUE TITLE
Can I use it without NuGet?

### ISSUE THREAD

**Issue by LazyWolfLin** [Microsoft/TestAdapterForGoogleTest#114]
TAFGT will get gtest package from NuGet. But I get gtest from vcpkg. Can I use TAFGT but don't get gtest again.
Thanks.

**Comment by LukaszMendakiewicz** [comment]
New Project templates provided by TAfGT indeed install NuGet package containing Google Test for the created project. There is currently no option to disable this behavior.

Having said that, TAfGT works with projects using Google Test which were not created using the provided project template (for example a project created by manually adding Google Test dependency to Win32 Console Application project should work), barring the limitations listed in [Known Issues](https://github.com/Microsoft/TestAdapterForGoogleTest/blob/d7e70313aec2ec41b151e4836585449fa8024fc3/GoogleTestAdapter/Packaging.TAfGT/ReleaseNotes.txt#L35).

Please let us know if anything does not work as expected.
