### ISSUE TITLE
GoogleTest 1.8.1.1 static.rt-dyn does not work

### ISSUE THREAD

**Issue by Stannieman** [microsoft/TestAdapterForGoogleTest#170]
A project using the latest version (from yesterday) does not build in debug mode. The .pdb files have the wrong name (don't have the "d" suffix like the libs do) or the targets file points to the wrong file.

Which makes me wonder, does anyone actually try to use this package before it's pushed to public NuGet repo?

**Comment by coxuintel** [comment]
Same issue here. Debug build now contains gtest.pdb and gtest_main.pdb, which are expected to be have the "d" suffix. Release build is fine.

Have to rollback to 1.8.1.

**Comment by coxuintel** [comment]
Looks like 1.8.1.2 resolved the issue.

**Comment by Stannieman** [comment]
Is it known what's changed in this 1.8.1.x versions? Cause GoogleTest itself does not seem to have such release.

**Comment by coxuintel** [comment]
d86835156b1294b09c2f92351b6cbca4d2674881

**Comment by ncook-hxgn** [comment]
I think this is a duplicate issue..?

**Comment by Stannieman** [comment]
No this one was first and just not closed when fixed in other one.
