### ISSUE TITLE
(193: %1 is not a valid Win32 application)

### ISSUE THREAD

**Issue by alastairUK** [Microsoft/TestAdapterForGoogleTest#18]
Installed the latest version. Now getting errors. Note: works fine from command line and previous version seemed to work OK - is there anyway to roll back to that version?

------ Load Playlist started ------
========== Load Playlist finished (0:00:00) ==========
------ Discover test started ------
Test Adapter for Google Test: Test discovery starting...
ERROR: Could not create process. Command: 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe', parameters: '--gtest_list_tests', working dir: '' (193: %1 is not a valid Win32 application)
ERROR: Could not list test cases of executable 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe': executing process failed with return code 2147483647
Command executed: 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe --gtest_list_tests', working directory: 'C:\Users\Me\Documents\Development\MyProject\Release'
Command produced no output
Found 0 tests in executable C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe
Test discovery completed, overall duration: 00:00:00.3644345
ERROR: ================
The following errors and warnings occured during test discovery (enable debug mode for more information):
ERROR: Could not create process. Command: 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe', parameters: '--gtest_list_tests', working dir: '' (193: %1 is not a valid Win32 application)
ERROR: Could not list test cases of executable 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe': executing process failed with return code 2147483647
Command executed: 'C:\Users\Me\Documents\Development\MyProject\Release\GoogleTests.exe --gtest_list_tests', working directory: 'C:\Users\Me\Documents\Development\MyProject\Release'
Command produced no output
========== Discover test finished: 0 found (0:00:00.610946) ==========

**Comment by alastairUK** [comment]
OK, I know what this is.

The actual location of the code is in 

'C:\Users\Firstname Lastname\Documents\Development\MyProject\Release\GoogleTests.exe

Note the space in the path.

If I move the code dir the c:\temp\ all works fine.

Should be a simple fix to add "" when calling the exe

**Comment by LukaszMendakiewicz** [comment]
I have trouble reproducing this issue. I have created new Google Test project from the template using the default settings in `C:\Users\Firstname Lastname\Documents\Development\MyProject`. After adjusting the regex for test discovery in Tools > Options to `.*` and building the project, the single test is correctly listed in Test Explorer.
Could you try these steps? If they work for you, what is different in your original problematic project?

**Comment by LukaszMendakiewicz** [comment]
I have found that the requirement for the bug to reproduce is that there is a file at the path `C:\Users\Firstname`.
Could you confirm that this is the case on your machine?
