### ISSUE TITLE
Do not ask msbuild to build project when executing tests

### ISSUE THREAD

**Issue by Lectem** [Microsoft/TestAdapterForGoogleTest#97]
We have a custom build step that checks/copies a lot of stuff and which is always triggered on build, even if no source file changed (because of new assets for example). 
The test project depends on the previous project as it links it, and we indeed want this build step when we build the test project. However, it is not needed if we only want to run the tests !

Would it be possible to have the option of not building the solution / test project when running tests from the Test Explorer window ? That way it would only used executables that are already built.

Or is there some environment variable set when running from TAfGT that we could test in our custom build step ?

Thanks!

**Comment by nickuhlenhuth** [comment]
Hi Lectem,
You could consider setting _Tools > Options > Project and Solutions > Build and Run > On Run, when projects are out of date_ to _Never Build_. This isn't a Test Explorer Window option today. While we don't currently have plans for this, please file a request through our [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html).
Cheers,
Nick
